---
apiVersion: v1
kind: List
items:

# Group will have some elevated permissions to deploy/maintain cluster-operator:
- apiVersion: user.openshift.io/v1
  kind: Group
  metadata:
    name: azure-team
  users:
  - mjudeikis
  - jim-minter
  - kargakis
  - pweil-

- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: admin
    namespace: azure
  groupNames:
  - aos-azure
  roleRef:
    name: admin
  subjects:
  - kind: Group
    name: aos-azure

- kind: ImageStream
  apiVersion: v1
  metadata:
    name: acs-engine-tests
    namespace: azure