kind: BuildConfig
apiVersion: v1
metadata:
  name: azure-purge-artifact
  namespace: azure
spec:
  successfulBuildsHistoryLimit: 1
  failedBuildsHistoryLimit: 2
  output:
    to:
      kind: ImageStreamTag
      name: "azure-purge-artifact:latest"
  source:
    contextDir: "src/go/"
    git:
      uri: "https://github.com/mjudeikis/azure-misc.git"
      ref: azure-purge-test
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile.azure-purge
      from:
        kind: DockerImage
        name: golang:1.10-alpine
      imageOptimizationPolicy: SkipLayers
  triggers:
  - type: ConfigChange
